module.exports = {
    STORE_DBURL: process.env.STORE_DBURL,
    STORE_DBNAME: process.env.STORE_DBNAME,
    STORE_COLLECTIONFROM: process.env.STORE_COLLECTIONFROM,
    STORE_COLLECTIONTO: process.env.STORE_COLLECTIONTO,
}